
services:
  mc:
    build: .
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      ONLINE_MODE: ${MINECRAFT_ONLINE_MODE}
      INIT_MEMORY: ${MINECRAFT_INIT_MEMORY}
      MAX_MEMORY: ${MINECRAFT_MAX_MEMORY}
      VERSION: ${MINECRAFT_VERSION}
      TYPE: ${MINECRAFT_TYPE}
    volumes:
      - ./data:/data
